<?php

defined( 'ABSPATH' ) || exit();

/*
* Load CSS & JS files
*/
function wpdocs_register_scripts() {
	wp_register_style('price-plan-global', TABLE_PRICE_ACF_ASSETS . '/css/price-plan-global.css' );
    wp_enqueue_style('price-plan-global');
	wp_register_script('toggle', TABLE_PRICE_ACF_ASSETS . '/js/toggle.js', array( 'wp-i18n' ) , '1.0', true);
	wp_enqueue_script( 'toggle' );
	// Get translations of string labels for toogles.js
	wp_localize_script('toggle', 'toggle_js_vars', array(
			'main_frequency' => get_field('main_frequency', 'option')["label"] ?? null,
			'second_frequency' => get_field('second_frequency', 'option')["label"] ?? null,
		)
	);
}
add_action('wp_enqueue_scripts', 'wpdocs_register_scripts');

/**
 * Create ACF option page if not yet exist
 **/
add_action('acf/init', 'my_acf_op_init');
function my_acf_op_init() {
	// Create page option if not yet exist
	$pagesOptionsAcf = acf_get_options_pages();
	if( function_exists('acf_add_options_page') || !in_array("table-price-acf-settings", $pagesOptionsAcf) ) {		 
		acf_add_options_page(array(
			'page_title' 	=> __('Table Price ACF', 'table-price-acf'),
			'menu_title'	=> __('Table Price ACF Settings', 'table-price-acf'),
			'menu_slug' 	=> 'table-price-acf-settings',
			'capability'	=> 'edit_posts',
			'icon_url' 		=> 'dashicons-editor-table',
			'redirect'		=> true
		));
		acf_add_options_sub_page(array(
			'page_title'    => __('Table Price ACF Content', 'table-price-acf'),			
			'menu_title'    => __('Content', 'table-price-acf'),
			'menu_slug' 	=> 'acf-options-content',
			'parent_slug'   => 'table-price-acf-settings',
		));

		acf_add_options_sub_page(array(
			'page_title'    => __('Table Price ACF Design', 'table-price-acf'),
			'menu_title'    => __('Design', 'table-price-acf'),
			'menu_slug' 	=> 'acf-options-design',
			'parent_slug'   => 'table-price-acf-settings',
		)); 	
	}
	// Create group field if not yet exist
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'price_plan_acf_content',
	'title' => __('Price Plan ACF', 'table-price-acf'),
	'fields' => array(
		array(
			'key' => 'field_62ee20d57bb4d',
			'label' => __('Main currency', 'table-price-acf'),
			'name' => 'main_currency',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_62ee20d57bb4e',
					'label' => __('ISO Code', 'table-price-acf'),
					'name' => 'iso_code',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'EUR',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_62ee20d57bb4f',
					'label' => __('Symbol', 'table-price-acf'),
					'name' => 'symbol_cur',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
			),
		),
		array(
			'key' => 'field_63e7cbead9269',
			'label' => __('Other currency', 'table-price-acf'),
			'name' => 'other_currency',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'ui' => 1,
		),
		array(
			'key' => 'field_62ec00d1bdaa2',
			'label' => __('Second currency', 'table-price-acf'),
			'name' => 'second_currency',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_63e7cbead9269',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'layout' => 'row',
			'sub_fields' => array(
				array(
					'key' => 'field_62ec00ebbdaa3',
					'label' => __('ISO Code', 'table-price-acf'),
					'name' => 'code_iso',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_62ec016bbdaa4',
					'label' => __('Symbol', 'table-price-acf'),
					'name' => 'symbol_cur',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_62ead17a06b53',
			'label' => __('Exchange rate', 'table-price-acf'),
			'name' => 'exchange-rate',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_63e7cbead9269',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '10.5',
			'maxlength' => 5,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_62ead17a0a618',
			'label' => __('Period multiplier', 'table-price-acf'),
			'name' => 'period_multiplier',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 11,
			'maxlength' => 5,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_63e7d45d7bc8f',
			'label' => __('Main frequency', 'table-price-acf'),
			'name' => 'main_frequency',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'week' => __('Week', 'table-price-acf'),
				'month' => __('Month', 'table-price-acf'),
				'quarter' => __('Quarter', 'table-price-acf'),
				'biannual' => __('Biannual', 'table-price-acf'),
				'annual' => __('Annual', 'table-price-acf'),
			),
			'default_value' => false,
			'return_format' => 'array',
			'multiple' => 0,
			'allow_null' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_63e8b7f9a94d8',
			'label' => __('Second frequency', 'table-price-acf'),
			'name' => 'second_frequency',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'week' => __('Week', 'table-price-acf'),
				'month' => __('Month', 'table-price-acf'),
				'quarter' => __('Quarter', 'table-price-acf'),
				'biannual' => __('Biannual', 'table-price-acf'),
				'annual' => __('Annual', 'table-price-acf'),
			),
			'default_value' => false,
			'return_format' => 'array',
			'multiple' => 0,
			'allow_null' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_62eaedad417ed',
			'label' => __('Plan', 'table-price-acf'),
			'name' => 'plan',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => __('Add an item', 'table-price-acf'),
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_62eaee37417ef',
					'label' => __('Plan title', 'table-price-acf'),
					'name' => 'title_plan',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'parent_repeater' => 'field_62eaedad417ed',
				),
				array(
					'key' => 'field_62ead179ebff1',
					'label' => __('Plan description', 'table-price-acf'),
					'name' => 'description_plan',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'parent_repeater' => 'field_62eaedad417ed',
				),
				array(
					'key' => 'field_62ead179ef9dd',
					'label' => __('Price', 'table-price-acf'),
					'name' => 'price',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => 5,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_62eaedad417ed',
				),
				array(
					'key' => 'field_62eb86383297b',
					'label' => __('Options plan', 'table-price-acf'),
					'name' => 'options_plan',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'table',
					'button_label' => __('Add an item', 'table-price-acf'),
					'rows_per_page' => 20,
					'parent_repeater' => 'field_62eaedad417ed',
					'sub_fields' => array(
						array(
							'key' => 'field_62eb86533297c',
							'label' => __('Available ?', 'table-price-acf'),
							'name' => 'available',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
							'ui' => 1,
							'parent_repeater' => 'field_62eb86383297b',
						),
						array(
							'key' => 'field_62eb86a03297d',
							'label' => __('Label option', 'table-price-acf'),
							'name' => 'label_option',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'parent_repeater' => 'field_62eb86383297b',
						),
					),
				),
				array(
					'key' => 'field_62eb8e5dd8e74',
					'label' => __('Featured', 'table-price-acf'),
					'name' => 'featured',
					'aria-label' => '',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
					'ui' => 1,
					'parent_repeater' => 'field_62eaedad417ed',
				),
				array(
					'key' => 'field_63e7d5527bc90',
					'label' => __('Link to buy', 'table-price-acf'),
					'name' => 'link_to_buy',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => __('Link to purchase or subscribe to this product/service', 'table-price-acf'),
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'parent_repeater' => 'field_62eaedad417ed',
				),
				array(
					'key' => 'field_63e946ec4f6df',
					'label' => __('Label link', 'table-price-acf'),
					'name' => 'label_link',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_63e7d5527bc90',
								'operator' => '!=empty',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_62eaedad417ed',
				),
			),
		),
		array(
			'key' => 'field_62ec0b6a4e7c3',
			'label' => __('Slogan', 'table-price-acf'),
			'name' => 'slogan',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-content',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
));

acf_add_local_field_group(array(
	'key' => 'price_plan_acf_design',
	'title' => __('Price Plan ACF Design', 'table-price-acf'),
	'fields' => array(
		array(
			'key' => 'field_63e8a660219ef',
			'label' => __('Plan', 'table-price-acf'),
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_63e804768bcdf',
			'label' => __('Background color', 'table-price-acf'),
			'name' => 'background_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => 'Default: #ffffff',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'rgba(255,255,255,1)',
			'enable_opacity' => 1,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_63e8a9a7854e6',
			'label' => __('Title color', 'table-price-acf'),
			'name' => 'title_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => 'Default: #3a3a3a',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#3a3a3a',
			'enable_opacity' => 0,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_63e8aa08854e8',
			'label' => __('Description color', 'table-price-acf'),
			'name' => 'description_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => 'Default: #6d708d',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#6d708d',
			'enable_opacity' => 0,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_63e8aa80854ea',
			'label' => __('Price color', 'table-price-acf'),
			'name' => 'price_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => 'Default: #00d09c',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#00d09c',
			'enable_opacity' => 0,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_63e8a6b6219f1',
			'label' => __('Font color', 'table-price-acf'),
			'name' => 'font_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => 'Default: #6d708d',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#6d708d',
			'enable_opacity' => 0,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_63e8a706219f2',
			'label' => __('Separate bar color', 'table-price-acf'),
			'name' => 'separate_bar_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => 'Default: #d6d6dc94',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'rgba(204,204,204,1)',
			'enable_opacity' => 1,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_63e8a722219f3',
			'label' => __('Featured plan', 'table-price-acf'),
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_63e8a737219f4',
			'label' => __('Background color feat', 'table-price-acf'),
			'name' => 'background_color_feat',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => 'Default: #702FFF',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'rgba(112,47,255,1)',
			'enable_opacity' => 1,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_63e8a9dc854e7',
			'label' => __('Title color feat', 'table-price-acf'),
			'name' => 'title_color_feat',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => 'Default: #ffffff',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#ffffff',
			'enable_opacity' => 0,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_63e8aa48854e9',
			'label' => __('Description color feat', 'table-price-acf'),
			'name' => 'description_color_feat',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => 'Default: #ffffff',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#ffffff',
			'enable_opacity' => 0,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_63e8aadb854eb',
			'label' => __('Price color feat', 'table-price-acf'),
			'name' => 'price_color_feat',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => 'Default: #00d09c',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#00d09c',
			'enable_opacity' => 0,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_63e8a73a219f5',
			'label' => __('Font color feat', 'table-price-acf'),
			'name' => 'font_color_feat',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => 'Default: #ffffff',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#ffffff',
			'enable_opacity' => 0,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_63e8a740219f6',
			'label' => __('Separate bar color feat', 'table-price-acf'),
			'name' => 'separate_bar_color_feat',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => 'Default: #d6d6dc94',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'rgba(204,204,204,1)',
			'enable_opacity' => 1,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_63e8ab1436693',
			'label' => __('Font size', 'table-price-acf'),
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_63e8ab3a36694',
			'label' => __('Title font size', 'table-price-acf'),
			'name' => 'title_font_size',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => 'Default: 18px',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 18,
			'min' => 1,
			'max' => '',
			'placeholder' => '',
			'step' => 1,
			'prepend' => '',
			'append' => 'px',
		),
		array(
			'key' => 'field_63e8abdb526e2',
			'label' => __('Description font size', 'table-price-acf'),
			'name' => 'description_font_size',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => 'Default: 17px',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 17,
			'min' => 1,
			'max' => '',
			'placeholder' => '',
			'step' => 1,
			'prepend' => '',
			'append' => 'px',
		),
		array(
			'key' => 'field_63e8ac1b526e3',
			'label' => __('Price font size', 'table-price-acf'),
			'name' => 'price_font_size',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => 'Default: 40px',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 40,
			'min' => 1,
			'max' => '',
			'placeholder' => '',
			'step' => 1,
			'prepend' => '',
			'append' => 'px',
		),
		array(
			'key' => 'field_63e8ac4b526e4',
			'label' => __('Body font size', 'table-price-acf'),
			'name' => 'body_font_size',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => 'Default: 17px',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 17,
			'min' => 1,
			'max' => '',
			'placeholder' => '',
			'step' => 1,
			'prepend' => '',
			'append' => 'px',
		),
		array(
			'key' => 'field_63e8ac89526e5',
			'label' => __('Separate border with', 'table-price-acf'),
			'name' => 'separate_border_width',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => 'Default: 2px',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 2,
			'min' => 0,
			'max' => '',
			'placeholder' => '',
			'step' => 1,
			'prepend' => '',
			'append' => 'px',
		),
		array(
			'key' => 'field_63e9f20bb2f20',
			'label' => __('Button', 'table-price-acf'),
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_63e9f2c0b2f22',
			'label' => __('Background button', 'table-price-acf'),
			'name' => 'background_button',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => 'Default: #ffffff',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#000248',
			'enable_opacity' => 1,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_63e9f33db2f23',
			'label' => __('Font color button', 'table-price-acf'),
			'name' => 'font_color_button',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => 'Default: #ffffff',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#ffffff',
			'enable_opacity' => 0,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_63e9f345b2f24',
			'label' => __('Background button hover', 'table-price-acf'),
			'name' => 'background_button_hover',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => 'Default: #ffffff',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#ffffff',
			'enable_opacity' => 1,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_63e9f37bb2f25',
			'label' => __('Font color button hover', 'table-price-acf'),
			'name' => 'font_color_button_hover',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => 'Default: #ffffff',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#000248',
			'enable_opacity' => 0,
			'return_format' => 'string',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-design',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
));

endif;
}

add_filter('acf/load_field', 'translate_acf_fields');
function translate_acf_fields( $field ) {
 
  // Don't run on acf-field-group page
  if( get_post_type( get_the_ID() ) == 'acf-field-group' ) {
    return $field;
  }

  // Translate backend labels/titles/instuctions
  $field['label']        = __( $field['label'], 'table-price-acf' );
  $field['instructions'] = __( $field['instructions'], 'table-price-acf' );
  $choices = $field['choices'] ?? null;
  if ($choices) :
	foreach ( $choices as $choice => $value ) {
		$field['choices'][$choice] = __( $field['choices'][$choice], 'table-price-acf' );
	}
	endif;
  return $field;
}